name: Run

on:
  workflow_dispatch:
  
  schedule:
    - cron: "0 6 * * *" # Run every day at 6:00 UTC 
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
             
    - name: Get LP42 Menu
      env:
        canteen_school_id: ${{ secrets.CANTEEN_SCHOOL_ID_LP42 }}
        canteen_username: ${{ secrets.CANTEEN_USERNAME }}
        canteen_password: ${{ secrets.CANTEEN_PASSWORD }}
        gist_write_pat: ${{ secrets.GIST_WRITE_PAT }}
        gist_id: ${{ secrets.GIST_ID }}
        gist_filename: "LP42.csv"
      run: dotnet run --project CanteenParser $canteen_school_id $canteen_username $canteen_password $gist_write_pat $gist_id $gist_filename

    - name: Get VTA Menu
      env:
        canteen_school_id: ${{ secrets.CANTEEN_SCHOOL_ID_VTA }}
        canteen_username: ${{ secrets.CANTEEN_USERNAME }}
        canteen_password: ${{ secrets.CANTEEN_PASSWORD }}
        gist_write_pat: ${{ secrets.GIST_WRITE_PAT }}
        gist_id: ${{ secrets.GIST_ID }}
        gist_filename: "VTA.csv"
      run: dotnet run --project CanteenParser $canteen_school_id $canteen_username $canteen_password $gist_write_pat $gist_id $gist_filename
      
    - name: Get VTD Menu
      env:
        canteen_school_id: ${{ secrets.CANTEEN_SCHOOL_ID_VTD }}
        canteen_username: ${{ secrets.CANTEEN_USERNAME }}
        canteen_password: ${{ secrets.CANTEEN_PASSWORD }}
        gist_write_pat: ${{ secrets.GIST_WRITE_PAT }}
        gist_id: ${{ secrets.GIST_ID }}
        gist_filename: "VTD.csv"
      run: dotnet run --project CanteenParser $canteen_school_id $canteen_username $canteen_password $gist_write_pat $gist_id $gist_filename

    - name: Get Maalov B9 Menu
      env:
        canteen_school_id: ${{ secrets.CANTEEN_SCHOOL_ID_B9 }}
        canteen_username: ${{ secrets.CANTEEN_USERNAME }}
        canteen_password: ${{ secrets.CANTEEN_PASSWORD }}
        gist_write_pat: ${{ secrets.GIST_WRITE_PAT }}
        gist_id: ${{ secrets.GIST_ID }}
        gist_filename: "B9.csv"
      run: dotnet run --project CanteenParser $canteen_school_id $canteen_username $canteen_password $gist_write_pat $gist_id $gist_filename

    - name: Get Kalundborg EG Menu
      env:
        canteen_school_id: ${{ secrets.CANTEEN_SCHOOL_ID_EG }}
        canteen_username: ${{ secrets.CANTEEN_USERNAME }}
        canteen_password: ${{ secrets.CANTEEN_PASSWORD }}
        gist_write_pat: ${{ secrets.GIST_WRITE_PAT }}
        gist_id: ${{ secrets.GIST_ID }}
        gist_filename: "EG.csv"
      run: dotnet run --project CanteenParser $canteen_school_id $canteen_username $canteen_password $gist_write_pat $gist_id $gist_filename

    - name: Get Kalundborg GE Menu
      env:
        canteen_school_id: ${{ secrets.CANTEEN_SCHOOL_ID_GE }}
        canteen_username: ${{ secrets.CANTEEN_USERNAME }}
        canteen_password: ${{ secrets.CANTEEN_PASSWORD }}
        gist_write_pat: ${{ secrets.GIST_WRITE_PAT }}
        gist_id: ${{ secrets.GIST_ID }}
        gist_filename: "GE.csv"
      run: dotnet run --project CanteenParser $canteen_school_id $canteen_username $canteen_password $gist_write_pat $gist_id $gist_filename

    - name: Get Kalundborg HB Menu
      env:
        canteen_school_id: ${{ secrets.CANTEEN_SCHOOL_ID_HB }}
        canteen_username: ${{ secrets.CANTEEN_USERNAME }}
        canteen_password: ${{ secrets.CANTEEN_PASSWORD }}
        gist_write_pat: ${{ secrets.GIST_WRITE_PAT }}
        gist_id: ${{ secrets.GIST_ID }}
        gist_filename: "HB.csv"
      run: dotnet run --project CanteenParser $canteen_school_id $canteen_username $canteen_password $gist_write_pat $gist_id $gist_filename
