name: Run

on:
  workflow_dispatch:
  
  schedule:
    - cron: "0 7 * * 1" # Run on Mondays at 8 UTC (9 CET) 
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
             
    - name: Get LP42 Menu
      if: always()
      env:
        canteen_school_id: ${{ secrets.CANTEEN_SCHOOL_ID_LP42 }}
        canteen_username: ${{ secrets.CANTEEN_USERNAME }}
        canteen_password: ${{ secrets.CANTEEN_PASSWORD }}
        gist_write_pat: ${{ secrets.GIST_WRITE_PAT }}
        gist_id: ${{ secrets.GIST_ID }}
        gist_filename: "LP42.csv"
        openAiKey: ${{ secrets.OPENAI_KEY }}
      run: dotnet run --project CanteenParser $canteen_school_id $canteen_username $canteen_password $openAiKey $gist_write_pat $gist_id $gist_filename

    - name: Get VTA Menu
      if: always()
      env:
        canteen_school_id: ${{ secrets.CANTEEN_SCHOOL_ID_VTA }}
        canteen_username: ${{ secrets.CANTEEN_USERNAME }}
        canteen_password: ${{ secrets.CANTEEN_PASSWORD }}
        gist_write_pat: ${{ secrets.GIST_WRITE_PAT }}
        gist_id: ${{ secrets.GIST_ID }}
        gist_filename: "VTA.csv"
        openAiKey: ${{ secrets.OPENAI_KEY }}
      run: dotnet run --project CanteenParser $canteen_school_id $canteen_username $canteen_password $openAiKey $gist_write_pat $gist_id $gist_filename
      
    - name: Get VTD Menu
      if: always()
      env:
        canteen_school_id: ${{ secrets.CANTEEN_SCHOOL_ID_VTD }}
        canteen_username: ${{ secrets.CANTEEN_USERNAME }}
        canteen_password: ${{ secrets.CANTEEN_PASSWORD }}
        gist_write_pat: ${{ secrets.GIST_WRITE_PAT }}
        gist_id: ${{ secrets.GIST_ID }}
        gist_filename: "VTD.csv"
        openAiKey: ${{ secrets.OPENAI_KEY }}
      run: dotnet run --project CanteenParser $canteen_school_id $canteen_username $canteen_password $openAiKey $gist_write_pat $gist_id $gist_filename

    - name: Get Maalov B9 Menu
      if: always()
      env:
        canteen_school_id: ${{ secrets.CANTEEN_SCHOOL_ID_B9 }}
        canteen_username: ${{ secrets.CANTEEN_USERNAME }}
        canteen_password: ${{ secrets.CANTEEN_PASSWORD }}
        gist_write_pat: ${{ secrets.GIST_WRITE_PAT }}
        gist_id: ${{ secrets.GIST_ID }}
        gist_filename: "B9.csv"
        openAiKey: ${{ secrets.OPENAI_KEY }}
      run: dotnet run --project CanteenParser $canteen_school_id $canteen_username $canteen_password $openAiKey $gist_write_pat $gist_id $gist_filename

    - name: Get Kalundborg EG Menu
      if: always()
      env:
        canteen_school_id: ${{ secrets.CANTEEN_SCHOOL_ID_EG }}
        canteen_username: ${{ secrets.CANTEEN_USERNAME }}
        canteen_password: ${{ secrets.CANTEEN_PASSWORD }}
        gist_write_pat: ${{ secrets.GIST_WRITE_PAT }}
        gist_id: ${{ secrets.GIST_ID }}
        gist_filename: "EG.csv"
        openAiKey: ${{ secrets.OPENAI_KEY }}
      run: dotnet run --project CanteenParser $canteen_school_id $canteen_username $canteen_password $openAiKey $gist_write_pat $gist_id $gist_filename

    - name: Get Kalundborg GE Menu
      if: always()
      env:
        canteen_school_id: ${{ secrets.CANTEEN_SCHOOL_ID_GE }}
        canteen_username: ${{ secrets.CANTEEN_USERNAME }}
        canteen_password: ${{ secrets.CANTEEN_PASSWORD }}
        gist_write_pat: ${{ secrets.GIST_WRITE_PAT }}
        gist_id: ${{ secrets.GIST_ID }}
        gist_filename: "GE.csv"
        openAiKey: ${{ secrets.OPENAI_KEY }}
      run: dotnet run --project CanteenParser $canteen_school_id $canteen_username $canteen_password $openAiKey $gist_write_pat $gist_id $gist_filename

    - name: Get Kalundborg HC Menu
      if: always()
      env:
        canteen_school_id: ${{ secrets.CANTEEN_SCHOOL_ID_HC }}
        canteen_username: ${{ secrets.CANTEEN_USERNAME }}
        canteen_password: ${{ secrets.CANTEEN_PASSWORD }}
        gist_write_pat: ${{ secrets.GIST_WRITE_PAT }}
        gist_id: ${{ secrets.GIST_ID }}
        gist_filename: "HC.csv"
        openAiKey: ${{ secrets.OPENAI_KEY }}
      run: dotnet run --project CanteenParser $canteen_school_id $canteen_username $canteen_password $openAiKey $gist_write_pat $gist_id $gist_filename

    - name: Get HJA Menu
      if: always()
      env:
        canteen_school_id: ${{ secrets.CANTEEN_SCHOOL_ID_HJA }}
        canteen_username: ${{ secrets.CANTEEN_USERNAME }}
        canteen_password: ${{ secrets.CANTEEN_PASSWORD }}
        gist_write_pat: ${{ secrets.GIST_WRITE_PAT }}
        gist_id: ${{ secrets.GIST_ID }}
        gist_filename: "HJA.csv"
        openAiKey: ${{ secrets.OPENAI_KEY }}
      run: dotnet run --project CanteenParser $canteen_school_id $canteen_username $canteen_password $openAiKey $gist_write_pat $gist_id $gist_filename

    - name: Get Hub1 Menu
      if: always()
      env:
        canteen_school_id: Hub1
        canteen_username: ${{ secrets.CANTEEN_USERNAME }}
        canteen_password: ${{ secrets.CANTEEN_PASSWORD }}
        gist_write_pat: ${{ secrets.GIST_WRITE_PAT }}
        gist_id: ${{ secrets.GIST_ID }}
        gist_filename: "HUB1.csv"
        openAiKey: ${{ secrets.OPENAI_KEY }}
      run: dotnet run --project CanteenParser $canteen_school_id $canteen_username $canteen_password $openAiKey $gist_write_pat $gist_id $gist_filename
      
