name: Run

on:
  workflow_dispatch:
  
  schedule:
    - cron: "0 6 * * *" # Run every day at 6:00 UTC 
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
             
    - name: Run
      env:
        canteen_username: ${{ secrets.CANTEEN_USERNAME }}
        canteen_password: ${{ secrets.CANTEEN_PASSWORD }}
        gist_write_pat: ${{ secrets.GIST_WRITE_PAT }}
        gist_id: ${{ secrets.GIST_ID }}
      run: dotnet run --project CanteenParser $canteen_username $canteen_password $gist_write_pat $gist_id
